version: '3.7'
services:
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
  service1:
    image: sophiec0s/service1:latest
    ports: 
    - target: 5000
      published: 5000
    networks:
      - ingress
    environment:
      DATABASE_URI: ${DATABASE_URI}
      SECRET_KEY: ${SECRET_KEY}
  service2:
    image: sophiec0s/service2:latest
    ports: 
    - target: 5001
      published: 5001
    networks:
      - ingress
  service3:
    image: sophiec0s/service3:latest
    ports: 
    - target: 5002
      published: 5002
    networks:
      - ingress
  service4:
    image: sophiec0s/service4:latest
    ports: 
    - target: 5003
      published: 5003
    networks:
      - ingress
  mysql:
    image: mysql:5.7
    ports: 
    - target: 3306
      published: 3306
      protocol: tcp
    volumes:
    - type: volume
      source: dbvolume
      target: /var/lib/mysql
    environment:
      MYSQL_DATABASE: sfia2
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
volumes:
  dbvolume:
networks:
  ingress:
    driver: overlay