version: '3.7'
services:
  nginx:
    image: sophiec0s/nginx:latest
    ports:
    - target: 80
      published: 80
    networks:
    - ingress
    deploy:
      replicas: 3
  service1:
    image: sophiec0s/service1:latest
    ports: 
    - target: 5000
      published: 5000
    networks:
    - ingress
    environment:
    - DATABASE_URI=${DATABASE_URI}
    - TEST_DB_URI=${TEST_DB_URI}
    deploy:
      replicas: 3
  service2:
    image: sophiec0s/service2:latest
    ports: 
    - target: 5001
      published: 5001
    networks:
    - ingress
    deploy: 
      replicas: 3
  service3:
    image: sophiec0s/service3:latest
    ports: 
    - target: 5002
      published: 5002
    networks:
    - ingress
    deploy:
      replicas: 3
  service4:
    image: sophiec0s/service4:latest
    ports: 
    - target: 5003
      published: 5003
    networks:
    - ingress
    deploy:
      replicas: 3
networks:
  ingress:
    driver: overlay