---
- hosts: 127.0.0.1
  connection: local
  become: true
  roles:
    - docker
- hosts: workers
  become: true
  roles:
    - docker
- name: initialize docker swarm
  become: true
  hosts: 127.0.0.1
  connection: local
  roles:
    - docker-swarm-init
  
- name: add workers to the swarm
  become: true 
  hosts: workers
  roles:
    - docker-swarm-add-worker
